### ISSUE TITLE
Does not compile in Arduino 1.8.13 with SparkFun Artemis Nano

### ISSUE THREAD

**Issue by jchiocca** [levkovigor/MMC34160PJ#1]
Hello,

I am having an issue with compilation in Arduino 1.8.13.  Library does not compile and returns:"Error: call of overloaded 'write(int)' is ambiguous" message.

Issue is resolved by adding (byte) cast operator to line 90 of MMC34160PJ.cpp.

Suggestion change line 90 to:

    _wire->write((byte) 0x00);

Best Wishes,

Joseph Chiocca

**Comment by levkovigor** [comment]
@jchiocca 

Thank you

Corrected in new Release 1.0.1
